### ISSUE TITLE
Generate GRUMP VectorTile pyramid

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-road-distance-sdg#13]
For the purpose of visualizing the results it would be helpful to see the polygons from [GRUMP](https://sedac.ciesin.columbia.edu/data/set/grump-v1-urban-ext-polygons-rev01) dataset. The most flexible way for web application is going to be to bake some VectorTile layers.

This can be done with https://github.com/mapbox/tippecanoe and saved to `un-sdg` or `com.azavea.datahub.tms` bucket. If using the `un-sdg` portion of it needs to be public enough to serve tiles form https.

**Comment by CloudNiner** [comment]
The tiles are publicly available at:

`https://a.tiles.azavea.com/grump-urban-extent-polygons/v1.01/{z}/{x}/{y}.pbf`, layer name `data`.

An example MapboxGL JS addSource + addLayer command:
```
map.addSource('grump', {
        "type": "vector",
        "tiles": [
          "https://a.tiles.azavea.com/grump-urban-extent-polygons/v1.01/{z}/{x}/{y}.pbf"
        ],
        "minzoom": 0,
        "maxzoom": 10
      });

      map.addLayer({
        "id": "grump-polygons",
        "type": "fill",
        "source": "grump",
        "source-layer": "data",
        "minzoom": 0,
        "maxzoom": 10,
        "paint": {
          "fill-color": "white"
        }
      }, 'waterway-label');
    });
```

yields:

![Screen Shot 2019-10-14 at 1 34 45 PM](https://user-images.githubusercontent.com/1818302/66771212-989e0800-ee87-11e9-8909-f8a0059f028b.png)


I generated and published the data using github.com/azavea/tiler-two:
```
export AWS_PROFILE=datahub
docker-compose run --rm \
    -v /Users/andrew/tmp/grump-vector-tiles:/data tiler-two \
    file:///data/global_urban_extent_polygons_v1.json \
    s3://tiles.us-east-1.azavea.com/grump-urban-extent-polygons/v1.01 \
    --tippecanoe-opts "--drop-densest-as-needed -zg --coalesce --reorder --hilbert"
```
