### ISSUE TITLE
Include Road statistics in result summary

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-road-distance-sdg#14]
- Summary of total KM of road by:
  - highway tag
  - surface tag
  - included in mask flag

The results can be filtered and combined to answer questions like:
- Total length of country road network?
- Percentage of road network included in calculation?
- Percentage of road network excluded by tag/surface
- What tags were excluded (useful for verification of completeness)

These results should be included in per-country JSON output

**Comment by echeipesh** [comment]
ref: https://github.com/geotrellis/geotrellis-road-distance-sdg/issues/14

**Comment by rossbernet** [comment]
Is it possible these results are in meters and not kilometers?

They seem roughly 1000x higher than the results I'd expect

https://docs.google.com/spreadsheets/d/1_NL7_FLt7uc5iMd3ogXHiy6j24KyXHZII-nZnM5rjOI/edit#gid=824042934
