### ISSUE TITLE
Stage WorldPop Rasters on S3

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-road-distance-sdg#2]
We're going to need access to all of WorldPop rasters on S3 so we can read and intersect them with OSM roads.

As mentioned on the WorldPop population page: https://www.worldpop.org/project/categories?id=3
There are couple of versions of the data. Looks like we should be using `Global Per Country 2000-2020` which is available at ~100m resolution. Other files we've been using from `Individual Countries` is described as the "old approach". 

Above files are available at `ftp://ftp.worldpop.org.uk/GIS/Population/Global_2000_2020`

This issue is to grab the 2019 files and put them somewhere on S3 for us to use.
For each year there exists `global_mosaic_ppp_100m_2019_vrt.zip` some kind of zipped mosaic. It would be worth while to check that out first to see if its an easy way to grab them for all countries.

*Note:* all countries for all years have `2018-11-01` as date of production so I'm a little unclear how `2020` dates were generated in 2018. I'm not clear if this is a prediction and where the line from historic tp prediction happens. Presumably this is described in here:

https://www.nature.com/articles/sdata20174
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0107042

**Comment by echeipesh** [comment]
After converting WorldPop to COGs I decided to make a bucket since its likely there are other aspects of WorldPop dataset we'll want to use.

Starting location is: `s3://azavea-worldpop/Population/Global_2000_2020/MOSAIC_2019/`
The files here came from `ftp://ftp.worldpop.org.uk/GIS/Population/Global_2000_2020/2019/0_Mosaicked/global_mosaic_ppp_100m_2019_vrt.zip` but unzipped and tiled. 

This was mostly an incidental choice and breaks way from WorldPop FTP it may be a better idea to mirror the unzipped country prefixed files in the future. Should be fine to get started though.

Commands to get COGs tiled:
```shell
 for file in *.tif; do gdal_translate $file "${file/.tif/_cog.tif}" -co TILED=YES -co COPY_SRC_OVERVIEWS=YES -co COMPRESS=LZW ; done
 for file in *.tif; do mv -f $file "${file/_cog.tif/.tif}"; done
```

**Comment by rossbernet** [comment]
@eneedham

Do you have access to this repo?

I want to make sure we are on the same page about which WorldPop and GRUMP datasets we are using
