### ISSUE TITLE
Convert GeoJson of countries with RAI values to vectortile layer

### ISSUE THREAD

**Issue by rossbernet** [geotrellis/geotrellis-road-distance-sdg#23]
We need to include a choropleth map of all countries and their RAI score (% rural pop further than 2km from road) on the final application. This will be more performant if it is a vectortile layer.

@echeipesh has already generated one geojson layer of countries, but we need to generate a new one with different tags being used for the final map.

**Comment by jfrankl** [comment]
Would it be possible to compute the bbox for each country and include it in the properties for that country? Ideally would be separate properties for west, south, east, north values. I'd be using this to zoom in on a country when it's clicked on.

**Comment by CloudNiner** [comment]
The latest geojson file was generated with the changes in https://github.com/geotrellis/geotrellis-road-distance-sdg/pull/37 and a vector tile layer was generated for it using:
```
AWS_PROFILE=geotrellis docker-compose run --rm -v $(pwd)/sample-data:/data tiler-two file:///data/cardno-countries.geojson s3://un-sdg/tiles/cardno-world-summary --tippecanoe-opts "--drop-densest-as-needed -zg --coalesce --reorder --hilbert"
```

This vector tile layer is available at:

https://un-sdg.s3.amazonaws.com/tiles/cardno-world-summary/{z}/{x}/{y}.pbf

for zoom levels 0 - 2. The properties should include everything available in the geojson file. I didn't filter anything out.
