### ISSUE TITLE
Publish pyramided png layer for 3 demo countries

### ISSUE THREAD

**Issue by rossbernet** [geotrellis/geotrellis-road-distance-sdg#33]
@eneedham generated rasters for three countries:

- Myanmar
- Nepal
- Malawi

The rasters are here:

https://drive.google.com/open?id=1N-gQ5AAOnOKHE9I9csKcRn_FH-LqeqAn

We need to generate a pyramided png tile set for each one of them.

**Comment by rossbernet** [comment]
should use the same breaks and color ramp that @CloudNiner uses for the global job:

```
.5,
1,
   2,
   5,
   10,
   50,
   100,
   1000,
   33000
```

**Comment by rossbernet** [comment]
Client pinged us with a new tif for Nepal - the worldpop estimate was off  by 30%.

Esther regenerated it with the 2km road mask, and I converted it the 0 values to no data:

https://drive.google.com/open?id=1k5Vi8-b9A3JmoZipM-5UnzbzZodRhZn7

We need to regenerate the png pyramid for nepal with the new tiff

**Comment by echeipesh** [comment]
https://tilejson.io/g/0905d257e2ad6fa40b8c97bdaf70c736/view

## Before
![Screen Shot 2019-11-06 at 12.55.25 PM.png](https://images.zenhubusercontent.com/5cc9fefa1e1b505674aa03b9/1b49be2e-9475-4a65-be20-da5aaaba654c)

## After
![Screen Shot 2019-11-06 at 1.12.07 PM.png](https://images.zenhubusercontent.com/5cc9fefa1e1b505674aa03b9/bde9bc78-d085-424c-9d56-45e19b0a9364)
