### ISSUE TITLE
Convert the road layers that Esther generated to VectorTiles

### ISSUE THREAD

**Issue by rossbernet** [geotrellis/geotrellis-road-distance-sdg#39]
Ross will gather up the roads and add a link to this issue, ensuring they are a geojson in lat/long that have one attribute of interest (included/not included)

@CloudNiner will convert to vector tile and store it in the appropriate location on s3.

**Comment by rossbernet** [comment]
@CloudNiner 

https://drive.google.com/open?id=1NzkCtc9grpPewCPMgMmyTKqY50stLk1F
GeoJson roads in epsg 4326 are ready in a zipped file at the above link

Should be in the correct format.  Let me know otherwise

There is one field we care about: `used` it has a value of 0/1. 
1 = used in calculation
0 = not used

If keeping the rest of the data doesnt make the tiles too big, great. Otherwise it can be dumped.

**Comment by CloudNiner** [comment]
These layers were generated via tiler-two using the command:
```
AWS_PROFILE=geotrellis docker-compose run --rm -v $(pwd)/sample-data:/data tiler-two file:///data/malawi_roads.geojson s3://un-sdg/tiles/cardno/MWI/country-data-roads --tippecanoe-opts "--drop-densest-as-needed -zg --coalesce --reorder --hilbert"
```

Substituting the appropriate country code and geojson file for each. The layers are available at:

## Malawi

https://un-sdg.s3.amazonaws.com/tiles/cardno/MWI/country-data-roads/{z}/{x}/{y}.png

## Myanmar

https://un-sdg.s3.amazonaws.com/tiles/cardno/MMR/country-data-roads/{z}/{x}/{y}.png

## Nepal

https://un-sdg.s3.amazonaws.com/tiles/cardno/NPL/country-data-roads/{z}/{x}/{y}.png
